#### Name: Peter Lucan
#### Student Number: C00228946

In [6]:
# Imports.
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.metrics import accuracy_score
from sklearn import tree

#Take in the data from the AdData.csv file.
dataSet = pd.read_csv('AdData.csv')
dataSet

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

# Data Pre Processing

In [7]:
# Drop the unecessary columns.
dataSet.drop('User ID', inplace=True, axis=1)
dataSet

Gender  Age  EstimatedSalary  Purchased
0      Male   19            19000          0
1      Male   35            20000          0
2    Female   26            43000          0
3    Female   27            57000          0
4      Male   19            76000          0
..      ...  ...              ...        ...
395  Female   46            41000          1
396    Male   51            23000          1
397  Female   50            20000          1
398    Male   36            33000          0
399  Female   49            36000          1

[400 rows x 4 columns]

In [8]:
# Renamimg colums to make it easier to work with.
dataSet = dataSet.rename(columns={'EstimatedSalary':'Salary'})
dataSet

Gender  Age  Salary  Purchased
0      Male   19   19000          0
1      Male   35   20000          0
2    Female   26   43000          0
3    Female   27   57000          0
4      Male   19   76000          0
..      ...  ...     ...        ...
395  Female   46   41000          1
396    Male   51   23000          1
397  Female   50   20000          1
398    Male   36   33000          0
399  Female   49   36000          1

[400 rows x 4 columns]

In [9]:
# Decision Trees only work with numerical values and not Labels so these must be encoded.
# We encode the values in the Gender Column to be 1 or 0 for male and female retrospectively.
genderL = LabelEncoder()
dataSet['Gender'] = genderL.fit_transform(dataSet['Gender'])
dataSet.head()

Gender  Age  Salary  Purchased
0       1   19   19000          0
1       1   35   20000          0
2       0   26   43000          0
3       0   27   57000          0
4       1   19   76000          0

In [10]:
# Check the shape of the data set. Number of rows and columns.
dataSet.shape

(400, 4)

In [11]:
# Check for null values in the data set.
dataSet.isnull().sum()

Gender       0
Age          0
Salary       0
Purchased    0
dtype: int64

In [12]:
# Seperate your Target and the rest of the data.
y = dataSet['Purchased']
X = dataSet.drop(['Purchased'], axis=1)

# Create the train andtest sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 101, stratify=y, test_size = 0.20)

# Check the distribution of the training set.
y_train.value_counts(normalize=True)

0    0.64375
1    0.35625
Name: Purchased, dtype: float64

In [13]:
# Check the distribution of the test set.
y_test.value_counts(normalize=True)

0    0.6375
1    0.3625
Name: Purchased, dtype: float64

In [14]:
# Check the shapes of the training sets.
X_train.shape, y_train.shape

((320, 3), (320,))

In [15]:
# Check the shapes of the test sets.
X_test.shape, y_test.shape

((80, 3), (80,))

In [16]:
# Create the decision tree function.
theModel = DecisionTreeClassifier(random_state=10)

# Fit the model.
theModel.fit(X_train, y_train)

DecisionTreeClassifier(random_state=10)

In [17]:
#Check the Training Score. (% of how accurate it is).
theModel.score(X_train, y_train)

1.0

In [18]:
#Check the Test Score. (% of how accurate it is).
theModel.score(X_test, y_test)

0.875

In [19]:
#Predictions for the test set.
theModel.predict(X_test)

array([0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0])

In [20]:
#The test set.
X_test = X_test.reset_index(drop=True)
X_test

Gender  Age  Salary
0        0   37   78000
1        1   30   80000
2        0   53  104000
3        1   40   57000
4        1   27   88000
..     ...  ...     ...
75       0   40  142000
76       1   35   61000
77       1   33   31000
78       0   56  104000
79       1   41   59000

[80 rows x 3 columns]

In [21]:
# Convert y_test into an array so we can put it into a data Frame.
y_testArray = y_test.values.reshape(-1,1)

# Save the predictions into x.
x = theModel.predict(X_test)

#Insert the y_test actual values and the predictions into the data frame.
X_test.insert(loc=3,column='Predictions', value=x)
X_test.insert(loc=4,column='ActualResults', value=y_testArray)
X_test

Gender  Age  Salary  Predictions  ActualResults
0        0   37   78000            0              1
1        1   30   80000            0              0
2        0   53  104000            1              1
3        1   40   57000            0              0
4        1   27   88000            0              0
..     ...  ...     ...          ...            ...
75       0   40  142000            1              1
76       1   35   61000            0              0
77       1   33   31000            0              0
78       0   56  104000            1              1
79       1   41   59000            0              0

[80 rows x 5 columns]

In [22]:
# Now we compare the two columns and save the results into the outcome datarame.
C = np.where( X_test['Predictions'] == X_test['ActualResults'], True, False)
outcome = pd.DataFrame(C, columns=['Result'])
outcome

Result
0    False
1     True
2     True
3     True
4     True
..     ...
75    True
76    True
77    True
78    True
79    True

[80 rows x 1 columns]

In [23]:
# Now we can view how many correct (True) and how many incorrect(flase) predictions we have.
outcome['Result'].value_counts()

True     70
False    10
Name: Result, dtype: int64

In [24]:
# Perroming simple math to verify the accuracy of the predictions (correct,incorrect)
# Should be the same as previously using theModel.score()
70/80,10/80

(0.875, 0.125)

In [ ]:
# Let's plot the entire Decision Tree for the full data set.
tree.plot_tree(theModel);

In [ ]:
# The decision tree is too large so we will only show the tree to a max depth of one level.
fig, axes = plt.subplots(nrows=1,ncols=1,figsize=(8,8),dpi=800)
tree.plot_tree(theModel,feature_names = X_train.columns, max_depth=1,filled=True);

In [ ]:
# To view different dpeths just change "the max_depth" value (default is the full tree).
fig, axes = plt.subplots(nrows=1,ncols=1,figsize=(8,8),dpi=800)
tree.plot_tree(theModel,feature_names = X_train.columns, max_depth=2,filled=True);

In [401]:
#Now let's make predictions on the full data set.
x2 = theModel.predict(X)
x2

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [402]:
finalDataFrame = dataSet
finalDataFrame.insert(loc=4,column='Predictions', value=x2)
finalDataFrame

Gender  Age  Salary  Purchased  Predictions
0         1   19   19000          0            0
1         1   35   20000          0            0
2         0   26   43000          0            0
3         0   27   57000          0            0
4         1   19   76000          0            0
..      ...  ...     ...        ...          ...
395       0   46   41000          1            0
396       1   51   23000          1            1
397       0   50   20000          1            1
398       1   36   33000          0            0
399       0   49   36000          1            1

[400 rows x 5 columns]

In [403]:
# Now we compare the two columns and save the results into the outcome2 datarame.
C2 = np.where( finalDataFrame['Predictions'] == finalDataFrame['Purchased'], True, False)
outcome2 = pd.DataFrame(C2, columns=['Result'])
outcome2

Result
0      True
1      True
2      True
3      True
4      True
..      ...
395   False
396    True
397    True
398    True
399    True

[400 rows x 1 columns]

In [404]:
# Now we can view how many correct (True) and how many incorrect(flase) predictions we have.
outcome2['Result'].value_counts()

True     390
False     10
Name: Result, dtype: int64

In [405]:
# Perroming simple math to verify the accuracy of the predictions (correct,incorrect)
390/400,10/400

(0.975, 0.025)

In [406]:
# To finish this Decision Tree Algorithim tutorial let's just verify the train set because practice makes perfect.
x3 = theModel.predict(X_train)
x3

array([0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,

In [407]:
# Convert y_train into an array so we can put it into a data Frame.
y_trainArray = y_train.values.reshape(-1,1)

#Insert the y_t actual values and the predictions into the data frame.
trainFrame = X_train
trainFrame.insert(loc=3,column='Predictions', value=x3)
trainFrame.insert(loc=4,column='ActualResults', value=y_trainArray)
trainFrame

Gender  Age  Salary  Predictions  ActualResults
298       1   45   79000            0              0
13        1   32   18000            0              0
301       1   48   74000            1              1
53        0   35   23000            0              0
61        1   25   87000            0              0
..      ...  ...     ...          ...            ...
196       0   30   79000            0              0
193       1   19   70000            0              0
121       1   37   72000            0              0
74        1   32   18000            0              0
294       0   35   57000            0              0

[320 rows x 5 columns]

In [411]:
# Now we compare the two columns and save the results into the outcome datarame.
C3 = np.where( trainFrame['Predictions'] == trainFrame['ActualResults'], True, False)
outcome3 = pd.DataFrame(C3, columns=['Result'])
outcome3

Result
0      True
1      True
2      True
3      True
4      True
..      ...
315    True
316    True
317    True
318    True
319    True

[320 rows x 1 columns]

In [412]:
# Now we can view how many correct (True) and how many incorrect(flase) predictions we have.
outcome3['Result'].value_counts()

True    320
Name: Result, dtype: int64

In [413]:
# Perroming simple math to verify the accuracy of the predictions (correct,incorrect)
# Should be the same as previously using theModel.score()
320/320

1.0

In [414]:
# The End!